"""Routing provenance models and validation helpers."""

from .cache import ROAD_ROUTE_CACHE_FILENAME, RoadRouteCache, load_road_route_cache, route_anchor_key
from .legacy_cache_audit import LEGACY_ROUTE_CACHE_AUDIT_FILENAME, audit_legacy_route_cache
from .matrix import (
    RouteMatrix,
    RouteMatrixCell,
    RouteMatrixCellMissing,
    RouteMatrixError,
    RouteMatrixMissing,
    RouteMatrixNotPublicationEligible,
    RouteMatrixValidationReport,
    SolverRouteMatrixAdapter,
    build_route_matrix_from_context,
    build_validated_route_matrix_from_cache,
    geodesic_fallback_matrix,
    load_route_matrix_from_cache,
    required_pairs_from_sequences,
    route_matrix_to_frame,
    route_minutes_from_matrix,
    route_result_for_sequence,
    validate_route_matrix,
    write_validated_route_matrix_artifacts,
)
from .models import RouteLegResult, RouteResult
from .provider import RouteLegRequest, RouteMatrixRequest, RoutingActivation, RoutingProvider, SnapResult
from .road_cache_builder import (
    OSRM_LOCAL_BASE_URL,
    OSRM_PUBLIC_BASE_URL,
    ROAD_ROUTE_CACHE_AUDIT_FILENAME,
    ROAD_ROUTE_REQUESTS_FILENAME,
    RoadRouteCacheBuildResult,
    build_road_route_cache_from_artifacts,
    fetch_osrm_payload,
    is_public_osrm_base_url,
    osrm_cache_key,
    osrm_route_url,
    validate_route_fetch_policy,
)

__all__ = [
    "OSRM_LOCAL_BASE_URL",
    "OSRM_PUBLIC_BASE_URL",
    "ROAD_ROUTE_CACHE_AUDIT_FILENAME",
    "ROAD_ROUTE_CACHE_FILENAME",
    "ROAD_ROUTE_REQUESTS_FILENAME",
    "LEGACY_ROUTE_CACHE_AUDIT_FILENAME",
    "RoadRouteCache",
    "RoadRouteCacheBuildResult",
    "RouteLegRequest",
    "RouteLegResult",
    "RouteMatrix",
    "RouteMatrixCell",
    "RouteMatrixCellMissing",
    "RouteMatrixError",
    "RouteMatrixMissing",
    "RouteMatrixNotPublicationEligible",
    "RouteMatrixRequest",
    "RouteMatrixValidationReport",
    "RouteResult",
    "RoutingActivation",
    "RoutingProvider",
    "SnapResult",
    "SolverRouteMatrixAdapter",
    "build_road_route_cache_from_artifacts",
    "build_validated_route_matrix_from_cache",
    "build_route_matrix_from_context",
    "audit_legacy_route_cache",
    "fetch_osrm_payload",
    "geodesic_fallback_matrix",
    "is_public_osrm_base_url",
    "load_road_route_cache",
    "load_route_matrix_from_cache",
    "osrm_cache_key",
    "required_pairs_from_sequences",
    "route_matrix_to_frame",
    "osrm_route_url",
    "route_anchor_key",
    "route_minutes_from_matrix",
    "route_result_for_sequence",
    "validate_route_matrix",
    "validate_route_fetch_policy",
    "write_validated_route_matrix_artifacts",
]
