"""Phase 0 research artifact contracts.

These dataclasses separate planner attempts, immutable plans, route validation,
and independent evaluation eligibility. They are intentionally lightweight so
existing pipeline code can adopt them incrementally.
"""

from __future__ import annotations

import hashlib
import json
from dataclasses import dataclass, field
from datetime import UTC, datetime
from typing import Any, Literal

from .routing.models import RouteResult

ExecutionStatus = Literal["COMPLETED", "FAILED", "FALLBACK_USED", "NOT_RUN"]
SolverCertification = Literal[
    "OPTIMALITY_CERTIFIED",
    "FEASIBILITY_CERTIFIED",
    "INCUMBENT_FEASIBILITY_CERTIFIED",
    "HEURISTIC_ONLY",
    "INVALIDATED_AFTER_EDIT",
    "NO_CERTIFICATE",
]
EvaluationStatus = Literal["PASSED", "PASSED_WITH_WARNINGS", "FAILED"]
EligibilityStatus = Literal["eligible", "ineligible"]


def stable_content_hash(payload: Any) -> str:
    """Return a stable short hash for JSON-compatible artifact payloads."""

    raw = json.dumps(payload, sort_keys=True, separators=(",", ":"), default=str)
    return hashlib.sha256(raw.encode("utf-8")).hexdigest()[:16]


@dataclass(frozen=True)
class PlannerRun:
    """One planner attempt, including failed or fallback runs."""

    run_id: str
    planning_request_id: str
    catalog_snapshot_id: str
    context_snapshot_id: str
    planner_specification_id: str
    method_requested: str
    method_executed: str
    execution_status: ExecutionStatus
    solver_certification: SolverCertification = "NO_CERTIFICATE"
    parent_run_id: str | None = None
    solver_backend: str = ""
    solver_version: str = ""
    fallback_reason: str = ""
    solver_status_raw: str = ""
    objective_value: float | None = None
    best_bound: float | None = None
    optimality_gap: float | None = None
    runtime_seconds: float | None = None
    result_plan_id: str | None = None
    error_class: str = ""
    error_summary: str = ""
    started_at: str = ""
    completed_at: str = ""
    schema_version: str = "planner-run-v1"

    @property
    def content_hash(self) -> str:
        return stable_content_hash(self.to_record(include_content_hash=False))

    @property
    def used_fallback(self) -> bool:
        return self.method_requested != self.method_executed or self.execution_status == "FALLBACK_USED"

    def to_record(self, *, include_content_hash: bool = True) -> dict[str, Any]:
        record = {
            "run_id": self.run_id,
            "parent_run_id": self.parent_run_id,
            "planning_request_id": self.planning_request_id,
            "catalog_snapshot_id": self.catalog_snapshot_id,
            "context_snapshot_id": self.context_snapshot_id,
            "planner_specification_id": self.planner_specification_id,
            "method_requested": self.method_requested,
            "method_executed": self.method_executed,
            "execution_status": self.execution_status,
            "solver_certification": self.solver_certification,
            "solver_backend": self.solver_backend,
            "solver_version": self.solver_version,
            "fallback_reason": self.fallback_reason,
            "solver_status_raw": self.solver_status_raw,
            "objective_value": self.objective_value,
            "best_bound": self.best_bound,
            "optimality_gap": self.optimality_gap,
            "runtime_seconds": self.runtime_seconds,
            "result_plan_id": self.result_plan_id,
            "error_class": self.error_class,
            "error_summary": self.error_summary,
            "started_at": self.started_at,
            "completed_at": self.completed_at,
            "schema_version": self.schema_version,
        }
        if include_content_hash:
            record["content_hash"] = self.content_hash
        return record


@dataclass(frozen=True)
class PlanArtifact:
    """Immutable plan content generated by a planner run or repair run."""

    plan_id: str
    source_run_id: str
    planning_request_id: str
    catalog_snapshot_id: str
    context_snapshot_id: str
    selected_stops: tuple[dict[str, Any], ...]
    parent_plan_id: str | None = None
    day_assignments: dict[str, int] = field(default_factory=dict)
    sequence: tuple[str, ...] = ()
    lodging_assignments: dict[str, str] = field(default_factory=dict)
    modeled_metrics: dict[str, float] = field(default_factory=dict)
    context_exposure_components: dict[str, float] = field(default_factory=dict)
    change_components: dict[str, float] = field(default_factory=dict)
    created_at: str = field(default_factory=lambda: datetime.now(UTC).isoformat())
    schema_version: str = "plan-artifact-v1"

    @property
    def content_hash(self) -> str:
        return stable_content_hash(self.to_record(include_content_hash=False))

    def to_record(self, *, include_content_hash: bool = True) -> dict[str, Any]:
        record = {
            "plan_id": self.plan_id,
            "parent_plan_id": self.parent_plan_id,
            "source_run_id": self.source_run_id,
            "planning_request_id": self.planning_request_id,
            "catalog_snapshot_id": self.catalog_snapshot_id,
            "context_snapshot_id": self.context_snapshot_id,
            "selected_stops": list(self.selected_stops),
            "day_assignments": self.day_assignments,
            "sequence": list(self.sequence),
            "lodging_assignments": self.lodging_assignments,
            "modeled_metrics": self.modeled_metrics,
            "context_exposure_components": self.context_exposure_components,
            "change_components": self.change_components,
            "created_at": self.created_at,
            "schema_version": self.schema_version,
        }
        if include_content_hash:
            record["content_hash"] = self.content_hash
        return record


@dataclass(frozen=True)
class ResearchEvaluationReport:
    """Independent eligibility report for final displayed plans."""

    evaluation_id: str
    evaluator_version: str
    plan_id: str
    source_run_id: str
    artifact_grounding_status: EvaluationStatus
    hard_feasibility_status: EvaluationStatus
    evaluation_status: EvaluationStatus
    comparison_eligibility: EligibilityStatus
    blocking_warning_count: int = 0
    nonblocking_warning_count: int = 0
    artifact_metrics: dict[str, float] = field(default_factory=dict)
    hard_metrics: dict[str, float] = field(default_factory=dict)
    soft_metrics: dict[str, float] = field(default_factory=dict)
    preference_metrics: dict[str, float] = field(default_factory=dict)
    conditional_reward: float | None = None
    evaluated_at: str = field(default_factory=lambda: datetime.now(UTC).isoformat())
    schema_version: str = "evaluation-report-v1"

    @property
    def reward_eligibility(self) -> bool:
        return self.comparison_eligibility == "eligible"

    @property
    def content_hash(self) -> str:
        return stable_content_hash(self.to_record(include_content_hash=False))

    def to_record(self, *, include_content_hash: bool = True) -> dict[str, Any]:
        record = {
            "evaluation_id": self.evaluation_id,
            "evaluator_version": self.evaluator_version,
            "plan_id": self.plan_id,
            "source_run_id": self.source_run_id,
            "artifact_grounding_status": self.artifact_grounding_status,
            "hard_feasibility_status": self.hard_feasibility_status,
            "evaluation_status": self.evaluation_status,
            "comparison_eligibility": self.comparison_eligibility,
            "blocking_warning_count": self.blocking_warning_count,
            "nonblocking_warning_count": self.nonblocking_warning_count,
            "artifact_metrics": self.artifact_metrics,
            "hard_metrics": self.hard_metrics,
            "soft_metrics": self.soft_metrics,
            "preference_metrics": self.preference_metrics,
            "conditional_reward": self.conditional_reward,
            "reward_eligibility": self.reward_eligibility,
            "evaluated_at": self.evaluated_at,
            "schema_version": self.schema_version,
        }
        if include_content_hash:
            record["content_hash"] = self.content_hash
        return record


def evaluate_phase0_plan(
    *,
    plan: PlanArtifact,
    planner_run: PlannerRun,
    route_result: RouteResult | None,
    dataset_snapshot_valid: bool,
    blocking_warning_count: int = 0,
    nonblocking_warning_count: int = 0,
) -> ResearchEvaluationReport:
    """Gate a plan before any soft/preference ranking is allowed."""

    artifact_failures = 0
    if not plan.selected_stops:
        artifact_failures += 1
    if plan.source_run_id != planner_run.run_id:
        artifact_failures += 1
    if plan.catalog_snapshot_id != planner_run.catalog_snapshot_id:
        artifact_failures += 1
    if plan.context_snapshot_id != planner_run.context_snapshot_id:
        artifact_failures += 1
    if not dataset_snapshot_valid:
        artifact_failures += 1

    hard_failures = 0
    if planner_run.execution_status not in {"COMPLETED", "FALLBACK_USED"}:
        hard_failures += 1
    if planner_run.solver_certification == "INVALIDATED_AFTER_EDIT":
        hard_failures += 1
    if route_result is None or not route_result.evaluation_eligible:
        hard_failures += 1

    artifact_status: EvaluationStatus = "PASSED" if artifact_failures == 0 else "FAILED"
    hard_status: EvaluationStatus = "PASSED" if hard_failures == 0 else "FAILED"
    eligible = artifact_status == "PASSED" and hard_status == "PASSED" and blocking_warning_count == 0
    evaluation_status: EvaluationStatus
    if not eligible:
        evaluation_status = "FAILED"
    elif nonblocking_warning_count:
        evaluation_status = "PASSED_WITH_WARNINGS"
    else:
        evaluation_status = "PASSED"

    return ResearchEvaluationReport(
        evaluation_id=f"eval_{plan.plan_id}",
        evaluator_version="phase0-evaluator-v1",
        plan_id=plan.plan_id,
        source_run_id=planner_run.run_id,
        artifact_grounding_status=artifact_status,
        hard_feasibility_status=hard_status,
        evaluation_status=evaluation_status,
        comparison_eligibility="eligible" if eligible else "ineligible",
        blocking_warning_count=blocking_warning_count,
        nonblocking_warning_count=nonblocking_warning_count,
        artifact_metrics={
            "artifact_failure_count": float(artifact_failures),
            "selected_stop_count": float(len(plan.selected_stops)),
        },
        hard_metrics={
            "hard_failure_count": float(hard_failures),
            "route_road_validated": float(bool(route_result and route_result.road_validated)),
            "route_evaluation_eligible": float(bool(route_result and route_result.evaluation_eligible)),
        },
        conditional_reward=1.0 if eligible else None,
    )

